"""Pydantic model for Item (Logistics) endpoint."""

from uuid import UUID

from pydantic import Field

from exact_online.models.base import ExactBaseModel, ODataDateTime


class Item(ExactBaseModel):
    """An item in Exact Online Logistics.

    Items are used in sales, purchase orders, shop orders, and more.
    Supports full CRUD operations (GET, POST, PUT, DELETE).
    """

    id: UUID = Field(alias="ID")
    code: str | None = Field(default=None, alias="Code")
    description: str | None = Field(default=None, alias="Description")
    extra_description: str | None = Field(default=None, alias="ExtraDescription")
    search_code: str | None = Field(default=None, alias="SearchCode")
    barcode: str | None = Field(default=None, alias="Barcode")
    item_group: UUID | None = Field(default=None, alias="ItemGroup")
    item_group_code: str | None = Field(default=None, alias="ItemGroupCode")
    item_group_description: str | None = Field(default=None, alias="ItemGroupDescription")
    is_sales_item: bool | None = Field(default=None, alias="IsSalesItem")
    is_purchase_item: bool | None = Field(default=None, alias="IsPurchaseItem")
    is_stock_item: bool | None = Field(default=None, alias="IsStockItem")
    is_serial_item: bool | None = Field(default=None, alias="IsSerialItem")
    is_batch_item: int | None = Field(default=None, alias="IsBatchItem")
    is_make_item: int | None = Field(default=None, alias="IsMakeItem")
    is_subcontracted_item: bool | None = Field(default=None, alias="IsSubcontractedItem")
    is_fraction_allowed_item: bool | None = Field(default=None, alias="IsFractionAllowedItem")
    is_time: int | None = Field(default=None, alias="IsTime")
    is_webshop_item: int | None = Field(default=None, alias="IsWebshopItem")
    is_on_demand_item: int | None = Field(default=None, alias="IsOnDemandItem")
    is_package_item: bool | None = Field(default=None, alias="IsPackageItem")
    stock: float | None = Field(default=None, alias="Stock")
    unit: str | None = Field(default=None, alias="Unit")
    unit_description: str | None = Field(default=None, alias="UnitDescription")
    unit_type: str | None = Field(default=None, alias="UnitType")
    average_cost: float | None = Field(default=None, alias="AverageCost")
    cost_price_standard: float | None = Field(default=None, alias="CostPriceStandard")
    cost_price_new: float | None = Field(default=None, alias="CostPriceNew")
    cost_price_currency: str | None = Field(default=None, alias="CostPriceCurrency")
    standard_sales_price: float | None = Field(default=None, alias="StandardSalesPrice")
    sales_vat_code: str | None = Field(default=None, alias="SalesVatCode")
    sales_vat_code_description: str | None = Field(default=None, alias="SalesVatCodeDescription")
    gl_costs: UUID | None = Field(default=None, alias="GLCosts")
    gl_costs_code: str | None = Field(default=None, alias="GLCostsCode")
    gl_costs_description: str | None = Field(default=None, alias="GLCostsDescription")
    gl_revenue: UUID | None = Field(default=None, alias="GLRevenue")
    gl_revenue_code: str | None = Field(default=None, alias="GLRevenueCode")
    gl_revenue_description: str | None = Field(default=None, alias="GLRevenueDescription")
    gl_stock: UUID | None = Field(default=None, alias="GLStock")
    gl_stock_code: str | None = Field(default=None, alias="GLStockCode")
    gl_stock_description: str | None = Field(default=None, alias="GLStockDescription")
    gross_weight: float | None = Field(default=None, alias="GrossWeight")
    net_weight: float | None = Field(default=None, alias="NetWeight")
    net_weight_unit: str | None = Field(default=None, alias="NetWeightUnit")
    copy_remarks: int | None = Field(default=None, alias="CopyRemarks")
    notes: str | None = Field(default=None, alias="Notes")
    picture_name: str | None = Field(default=None, alias="PictureName")
    picture_url: str | None = Field(default=None, alias="PictureUrl")
    picture_thumbnail_url: str | None = Field(default=None, alias="PictureThumbnailUrl")
    security_level: int | None = Field(default=None, alias="SecurityLevel")
    class_01: str | None = Field(default=None, alias="Class_01")
    class_02: str | None = Field(default=None, alias="Class_02")
    class_03: str | None = Field(default=None, alias="Class_03")
    class_04: str | None = Field(default=None, alias="Class_04")
    class_05: str | None = Field(default=None, alias="Class_05")
    class_06: str | None = Field(default=None, alias="Class_06")
    class_07: str | None = Field(default=None, alias="Class_07")
    class_08: str | None = Field(default=None, alias="Class_08")
    class_09: str | None = Field(default=None, alias="Class_09")
    class_10: str | None = Field(default=None, alias="Class_10")
    free_bool_field_01: bool | None = Field(default=None, alias="FreeBoolField_01")
    free_bool_field_02: bool | None = Field(default=None, alias="FreeBoolField_02")
    free_bool_field_03: bool | None = Field(default=None, alias="FreeBoolField_03")
    free_bool_field_04: bool | None = Field(default=None, alias="FreeBoolField_04")
    free_bool_field_05: bool | None = Field(default=None, alias="FreeBoolField_05")
    free_date_field_01: ODataDateTime = Field(default=None, alias="FreeDateField_01")
    free_date_field_02: ODataDateTime = Field(default=None, alias="FreeDateField_02")
    free_date_field_03: ODataDateTime = Field(default=None, alias="FreeDateField_03")
    free_date_field_04: ODataDateTime = Field(default=None, alias="FreeDateField_04")
    free_date_field_05: ODataDateTime = Field(default=None, alias="FreeDateField_05")
    free_number_field_01: float | None = Field(default=None, alias="FreeNumberField_01")
    free_number_field_02: float | None = Field(default=None, alias="FreeNumberField_02")
    free_number_field_03: float | None = Field(default=None, alias="FreeNumberField_03")
    free_number_field_04: float | None = Field(default=None, alias="FreeNumberField_04")
    free_number_field_05: float | None = Field(default=None, alias="FreeNumberField_05")
    free_number_field_06: float | None = Field(default=None, alias="FreeNumberField_06")
    free_number_field_07: float | None = Field(default=None, alias="FreeNumberField_07")
    free_number_field_08: float | None = Field(default=None, alias="FreeNumberField_08")
    free_text_field_01: str | None = Field(default=None, alias="FreeTextField_01")
    free_text_field_02: str | None = Field(default=None, alias="FreeTextField_02")
    free_text_field_03: str | None = Field(default=None, alias="FreeTextField_03")
    free_text_field_04: str | None = Field(default=None, alias="FreeTextField_04")
    free_text_field_05: str | None = Field(default=None, alias="FreeTextField_05")
    free_text_field_06: str | None = Field(default=None, alias="FreeTextField_06")
    free_text_field_07: str | None = Field(default=None, alias="FreeTextField_07")
    free_text_field_08: str | None = Field(default=None, alias="FreeTextField_08")
    free_text_field_09: str | None = Field(default=None, alias="FreeTextField_09")
    free_text_field_10: str | None = Field(default=None, alias="FreeTextField_10")
    division: int | None = Field(default=None, alias="Division")
    created: ODataDateTime = Field(default=None, alias="Created")
    creator: UUID | None = Field(default=None, alias="Creator")
    creator_full_name: str | None = Field(default=None, alias="CreatorFullName")
    modified: ODataDateTime = Field(default=None, alias="Modified")
    modifier: UUID | None = Field(default=None, alias="Modifier")
    modifier_full_name: str | None = Field(default=None, alias="ModifierFullName")
    start_date: ODataDateTime = Field(default=None, alias="StartDate")
    end_date: ODataDateTime = Field(default=None, alias="EndDate")
